name: 'ClickUp Release Tagging Action'
description: 'Tags ClickUp tasks with release name when a release is created'
author: 'Bravoure'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}
  clickup-api-key:
    description: 'ClickUp API Key'
    required: true
  tag-prefix:
    description: 'Prefix to add before the release name in the ClickUp tag (e.g., "Release: ")'
    required: false
    default: 'Release: '
  include-previous-release:
    description: 'Whether to include commits from the previous release to this one (true) or just this release (false)'
    required: false
    default: 'true'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'tag'
  color: 'blue'
